#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_godot_ai_model = env_modules.Clone()
env_godot_ai_model.add_source_files(env.modules_sources, "*.cpp")
